In [1]:
import os
from os.path import join
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal 
from matplotlib.ticker import NullFormatter
import sys
from PIL import Image
import os

In [2]:
os.getcwd()

'/home/crpbn/Desktop/Computational_Chem_Research/Tri_data'

In [3]:
"%cd .."

'%cd ..'

In [4]:
#creating columns for a dataframe
l = ['Center Number', 'Atomic Number', 'Atomic Type', 'X', 'Y', 'Z', 'E(RPBE1PBE)', 'Molecule']
#creating an empty df
coords_df = pd.DataFrame(columns = l)

for (dirname, dirs, files) in os.walk('.'):
    for filename in files:                       #looping through files in a directory
        #getting the path and folder name
        dirpath = os.getcwd()
        #print("current directory is : " + dirpath)
        foldername = os.path.basename(dirpath)
        #print("Directory name is : " + foldername)
        
        if filename.endswith('.log'):            #choosing only log files
            #reading file     
            file = open(os.path.join(dirname, filename), "r")
            #print(3)
            print('')                            #line to use as a process probe
            print(str(dirname))                  #line to use as a process probe

            #a flag for boolean decision; will help to identify sections
            #section_flag = False
            
            tables_num = 0
            energies_num = 0
            for line in file:                              #parsing lines in a log file; 1st time
                #print(4)
                #if re.search('^ Frequencies', line):       #processing Frequencies line 
                if re.search('^ *Standard orientation:', line):  ##counting std orient. tables
                    tables_num += 1
                elif re.search('^ SCF Done', line):         #counting SCF lines
                    energies_num += 1
            #print('UUU')
            con3 = 0
            con4 = 0
            #print('tables_num', tables_num)
            
            file.seek(0)        #rewinding the file
            
            for line in file:
               # print(5)
                if re.search('^ *Standard orientation:', line):
                    con3 += 1
                    #print('con3', con3)
                if con3 == tables_num and re.search('^\s\s\s\s\s.\d\s*\d', line):
                    ##print(6)
                    ser = pd.Series(line.split()+['',''], index=l)                  #create a pd.Series object...
                    coords_df = coords_df.append(ser, ignore_index=True)          #
                elif con3 == tables_num and re.search('^ SCF Done', line):
                    #print(7)
                    line = line.split()        
                    #add to the df
                    coords_df['E(RPBE1PBE)'][len(coords_df)-84:] = pd.Series(((line[4]+' ')*84).split())#, index = coords_df.index)
                    coords_df['Molecule'][len(coords_df)-84:] = pd.Series(((str(dirname[2:])+' ')*84).split()) 
                    break    

            file.close()                                   #closing the file
            print('File Done!')
            print('coords_df contains: '+str(len(coords_df))+' rows')
            #print('FIR_df contains: '+str(energies_num)+' SCF line')
        else:
            pass

./Tri_A154_ga09
File Done!
coords_df contains: 84 rows

./Tri_A154_ga01
File Done!
coords_df contains: 168 rows

./Tri_A154_ga07
File Done!
coords_df contains: 252 rows

./Tri_A154_ga13
File Done!
coords_df contains: 336 rows

./Tri_A154_0000
File Done!
coords_df contains: 420 rows

./Tri_A154_0001
File Done!
coords_df contains: 504 rows

./Tri_A154_0004
File Done!
coords_df contains: 588 rows

./Tri_A154_0008
File Done!
coords_df contains: 672 rows

./Tri_A154_0046
File Done!
coords_df contains: 756 rows

./Tri_A154_ga15
File Done!
coords_df contains: 840 rows

./Tri_A154_ga20
File Done!
coords_df contains: 924 rows

./Tri_A154_0007
File Done!
coords_df contains: 1008 rows

./Tri_A154_ga06
File Done!
coords_df contains: 1092 rows

./Tri_A154_ga03
File Done!
coords_df contains: 1176 rows

./Tri_A154_ga05
File Done!
coords_df contains: 1260 rows

./Tri_A154_0014
File Done!
coords_df contains: 1344 rows

./Tri_A154_ga16
File Done!
coords_df contains: 1428 rows

./Tri_A154_0034
File Done!
coords_df contains: 1512 rows

./Tri_A154_ga02
File Done!
coords_df contains: 1596 rows

./Tri_A154_ga12
File Done!
coords_df contains: 1680 rows

./Tri_A154_0140
File Done!
coords_df contains: 1764 rows

./Tri_A154_0047
File Done!
coords_df contains: 1848 rows

./Tri_A154_0006
File Done!
coords_df contains: 1932 rows

./Tri_A154_0051
File Done!
coords_df contains: 2016 rows

./Tri_A154_0041
File Done!
coords_df contains: 2100 rows

./Tri_A154_ga11
File Done!
coords_df contains: 2184 rows

./Tri_A154_0002
File Done!
coords_df contains: 2268 rows

./Tri_A154_0132
File Done!
coords_df contains: 2352 rows

./Tri_A154_0010
File Done!
coords_df contains: 2436 rows

./Tri_A154_ga04
File Done!
coords_df contains: 2520 rows

./Tri_A154_ga17
File Done!
coords_df contains: 2604 rows

./Tri_A154_0003
File Done!
coords_df contains: 2688 rows

./Tri_A154_ga14
File Done!
coords_df contains: 2772 rows

./Tri_A154_ga19
File Done!
coords_df contains: 2856 rows

./Tri_A154_ga18
File Done!
coords_df contains: 2940 rows

./Tri_A154_ga10
File Done!
coords_df contains: 3024 rows

./Tri_A154_ga08
File Done!
coords_df contains: 3108 rows

./Tri_A154_0060
File Done!
coords_df contains: 3192 rows

./Tri_A154_0024
File Done!
coords_df contains: 3276 rows

In [5]:
coords_df.head(5)

,Center Number,Atomic Number,Atomic Type,X,Y,Z,E(RPBE1PBE),Molecule
0,1,8,0,2.107017,1.528947,0.360723,-2159.40143903,Tri_A154_ga09
1,2,6,0,2.969213,0.427098,0.216815,-2159.40143903,Tri_A154_ga09
2,3,6,0,3.739042,0.551721,-1.094809,-2159.40143903,Tri_A154_ga09
3,4,6,0,4.563468,1.825350,-1.067774,-2159.40143903,Tri_A154_ga09
4,5,6,0,3.689264,3.026712,-0.754952,-2159.40143903,Tri_A154_ga09

In [6]:
df_1= coords_df.copy()
print(df_1.shape)
print(type(df_1))
df_1.head(5)

(3276, 8)
<class 'pandas.core.frame.DataFrame'>

,Center Number,Atomic Number,Atomic Type,X,Y,Z,E(RPBE1PBE),Molecule
0,1,8,0,2.107017,1.528947,0.360723,-2159.40143903,Tri_A154_ga09
1,2,6,0,2.969213,0.427098,0.216815,-2159.40143903,Tri_A154_ga09
2,3,6,0,3.739042,0.551721,-1.094809,-2159.40143903,Tri_A154_ga09
3,4,6,0,4.563468,1.825350,-1.067774,-2159.40143903,Tri_A154_ga09
4,5,6,0,3.689264,3.026712,-0.754952,-2159.40143903,Tri_A154_ga09

In [7]:
df_3 = pd.read_csv("DF1.csv")

In [8]:
df_3= df_3.iloc[:,1:8]
df_4= df_3.copy()
print(df_3.shape)
df_3.head(5)

(268632, 7)

        Molecule  Freq. A  Freq. B  Freq. C  IR Int. A  IR Int. B  IR Int. C
0  Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919
1  Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919
2  Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919
3  Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919
4  Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919

In [9]:
df_4 = df_4.set_index("Molecule", drop = True)
df_4.head(5)
df_4.drop_duplicates(subset=['Freq. A','Freq. B','Freq. C','IR Int. A','IR Int. B','IR Int. C'], keep='first', inplace=True)

In [10]:
df_4.head(5)

                Freq. A   Freq. B   Freq. C  IR Int. A  IR Int. B  IR Int. C
Molecule
Tri_A154_ga09   24.4027   28.7045   40.4046     0.2647     0.1846     2.3919
Tri_A154_ga09   49.6654   56.6175   66.7419     0.5382     1.9962     4.2701
Tri_A154_ga09   71.6761   78.2277   83.1775     0.9426     0.5547     2.2929
Tri_A154_ga09   95.9620   99.5544  114.4385     0.8758     2.5075     1.0339
Tri_A154_ga09  119.2536  126.6693  132.6148     6.7238     2.3797     4.5462

In [11]:
df_1 = df_1.set_index("Molecule", drop = True)
print(df_1.shape)
df_1.head(5)

(3276, 7)

,Center Number,Atomic Number,Atomic Type,X,Y,Z,E(RPBE1PBE)
Molecule,,,,,,,
Tri_A154_ga09,1,8,0,2.107017,1.528947,0.360723,-2159.40143903
Tri_A154_ga09,2,6,0,2.969213,0.427098,0.216815,-2159.40143903
Tri_A154_ga09,3,6,0,3.739042,0.551721,-1.094809,-2159.40143903
Tri_A154_ga09,4,6,0,4.563468,1.825350,-1.067774,-2159.40143903
Tri_A154_ga09,5,6,0,3.689264,3.026712,-0.754952,-2159.40143903

In [12]:
df_3 = df_3.set_index("Molecule", drop = True)
print(df_3.shape)
df_3.head(5)

(268632, 6)

               Freq. A  Freq. B  Freq. C  IR Int. A  IR Int. B  IR Int. C
Molecule
Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919
Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919
Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919
Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919
Tri_A154_ga09  24.4027  28.7045  40.4046     0.2647     0.1846     2.3919

In [13]:
df_combo= df_3.join(df_1)
print(df_combo.shape)
df_combo.head(5)

(22565088, 13)

,Freq. A,Freq. B,Freq. C,IR Int. A,IR Int. B,IR Int. C,Center Number,Atomic Number,Atomic Type,X,Y,Z,E(RPBE1PBE)
Molecule,,,,,,,,,,,,,
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,1,8,0,-1.545135,2.148028,-0.546319,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,2,6,0,-2.328377,1.572381,0.474567,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,3,6,0,-1.705724,1.826978,1.838963,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,4,6,0,-1.478224,3.309982,2.060614,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,5,6,0,-0.671363,3.903198,0.911391,-2159.40072251

In [14]:
df_combo1= df_combo.drop(df_combo.columns[[6, 8]], axis=1)
df_combo1

,Freq. A,Freq. B,Freq. C,IR Int. A,IR Int. B,IR Int. C,Atomic Number,X,Y,Z,E(RPBE1PBE)
Molecule,,,,,,,,,,,
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,-1.545135,2.148028,-0.546319,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-2.328377,1.572381,0.474567,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-1.705724,1.826978,1.838963,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-1.478224,3.309982,2.060614,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-0.671363,3.903198,0.911391,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-1.333707,3.543885,-0.411907,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-0.591754,3.967823,-1.678090,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,0.445258,3.080208,-2.024749,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,0.673268,3.441183,0.991422,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,-0.738162,3.544348,3.239076,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,-2.523514,1.362703,2.876046,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,-2.289536,0.204317,0.257243,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-3.475012,-0.508231,-0.075357,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-3.544189,-1.707712,0.846974,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,-3.643348,-1.255321,2.183441,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-2.287451,-2.543330,0.670422,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-1.950569,-2.824340,-0.804619,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,-2.088646,-1.672639,-1.628815,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-3.342673,-1.020296,-1.503141,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,-3.375856,0.085202,-2.540707,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,-4.571418,0.805646,-2.326820,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,-0.652524,-3.302005,-0.980755,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,0.401002,-2.515213,-0.457878,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,1.189117,-3.330541,0.553092,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,2.349393,-2.505796,1.076645,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,3.201827,-1.967459,-0.059789,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,2.401819,-1.300749,-1.015285,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,1.335857,-2.054922,-1.580780,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,6,0.664440,-1.130932,-2.578940,-2159.40072251
Tri_A154_0000,26.7912,29.3752,46.8679,0.2582,0.9524,1.1389,8,0.166433,0.046227,-1.951779,-2159.40072251
...,...,...,...,...,...,...,...,...,...,...,...
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,1.990194,-1.277872,-0.918790,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,1.944944,-3.891611,0.628772,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,3.065948,-2.366300,2.660515,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,1.560497,-1.405784,4.175448,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,2.679017,-0.097279,3.765543,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,0.932272,0.597686,2.261288,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-0.124487,-1.117009,0.047610,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-1.119248,-2.791259,-2.300956,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-1.628709,0.158973,-1.719854,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-3.630923,-2.150189,-1.694496,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-2.214986,-3.336468,-0.028006,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-2.691728,-2.820734,2.241662,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-0.938691,-3.077656,2.117635,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-0.645589,-0.910936,2.596608,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-5.284041,-1.019208,0.041519,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-5.939161,-1.046778,-1.606972,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-7.063559,0.640148,-0.147796,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-6.341484,1.346589,-1.583435,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-5.855644,2.801765,0.288032,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-4.389074,2.100784,-0.329656,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-4.949310,0.287726,1.706881,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-5.726626,1.714002,2.350641,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-3.506098,2.965005,1.923313,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-3.445406,1.715751,3.176409,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-2.807883,1.019189,0.407884,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-2.324101,0.231508,1.776228,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-1.604874,1.668440,1.362798,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,-2.833879,-0.109224,-3.668124,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,0.105306,-1.221823,-3.450556,-2159.39554685
Tri_A154_ga20,3875.2118,3878.5179,3897.4010,71.9845,60.0865,67.0321,1,2.117847,-2.996064,-2.266392,-2159.39554685

In [15]:
df_3
df_A154_00= df_4.loc["Tri_A154_0000", : ]
print(df_A154_00.shape)
df_A154_00.head(5)

(82, 6)

                Freq. A   Freq. B   Freq. C  IR Int. A  IR Int. B  IR Int. C
Molecule
Tri_A154_0000   26.7912   29.3752   46.8679     0.2582     0.9524     1.1389
Tri_A154_0000   52.9486   59.0117   63.7388     1.4402     1.1100     0.6913
Tri_A154_0000   72.1372   75.4755   86.6031     0.1184     2.3246     1.3013
Tri_A154_0000   90.1752   97.6698  104.2669     3.4640     3.5862     4.9617
Tri_A154_0000  113.3914  123.6386  135.1285     3.0183     2.2457     0.8910

In [16]:
dfA24IR_A= df_A154_00.loc["Tri_A154_0000", ['IR Int. A']]
print('1) dfA24IRF_A: ' + str((dfA24IR_A.shape)))
dfA24F_A= df_A154_00.loc["Tri_A154_0000", ['Freq. A']]
print('3) dfA24F_A: ' + str((dfA24F_A.shape)))

dfA24IR_B= df_A154_00.loc["Tri_A154_0000", ['IR Int. B']]
print('4) dfA24IRF_B: ' + str((dfA24IR_B.shape)))
dfA24F_B= df_A154_00.loc["Tri_A154_0000", ['Freq. B']]
print('6) dfA24F_B: ' + str((dfA24F_B.shape)))

dfA24IR_C= df_A154_00.loc["Tri_A154_0000", ['IR Int. C']]
print('7) dfA24IRF_C: ' + str((dfA24IR_C.shape)))
dfA24F_C= df_A154_00.loc["Tri_A154_0000", ['Freq. C']]
print('9) dfA24F_C: ' + str((dfA24F_C.shape)))

1) dfA24IRF_A: (82, 1)
3) dfA24F_A: (82, 1)
4) dfA24IRF_B: (82, 1)
6) dfA24F_B: (82, 1)
7) dfA24IRF_C: (82, 1)
9) dfA24F_C: (82, 1)

In [17]:
dfA24IR_A.index = pd.RangeIndex(len(dfA24IR_A.index))
dfA24F_A.index = pd.RangeIndex(len(dfA24F_A.index))
dfA24IR_A.head(5)
print(dfA24IR_A.dtypes)
dfA24F_A.head(5)

IR Int. A    float64
dtype: object

    Freq. A
0   26.7912
1   52.9486
2   72.1372
3   90.1752
4  113.3914

In [18]:
dfA24IR_Ai= pd.to_numeric(dfA24IR_A['IR Int. A'])
dfA24IR_Ai= dfA24IR_Ai.values.T.tolist()
dfA24IR_Ai

[0.2582,
 1.4402,
 0.1184,
 3.464,
 3.0183,
 3.6723,
 11.5623,
 4.5454,
 104.7302,
 4.2934,
 3.7284,
 1.3136,
 0.3818,
 9.4513,
 12.3576,
 15.848,
 14.6828,
 61.096,
 7.1023,
 2.1818,
 18.9496,
 46.4913,
 33.8535,
 120.1547,
 18.9948,
 56.6947,
 25.9996,
 3.9647,
 3.6619,
 6.2611,
 17.731,
 17.5526,
 2.4254,
 13.7292,
 60.6381,
 56.156,
 30.2151,
 137.4607,
 85.8338,
 194.7578,
 140.9609,
 116.654,
 43.5648,
 3.401,
 62.7609,
 84.0375,
 1.7094,
 45.3409,
 29.719,
 11.5213,
 2.4229,
 0.6632,
 71.0259,
 21.0917,
 33.1501,
 18.4097,
 38.4008,
 4.9237,
 7.7688,
 16.7824,
 6.9295,
 3.9709,
 10.2067,
 7.4927,
 10.5308,
 8.4841,
 12.9248,
 68.3337,
 8.3713,
 5.5106,
 23.5755,
 18.3505,
 28.5058,
 17.4785,
 6.5958,
 40.4661,
 6.676,
 7.4542,
 604.0111,
 298.644,
 167.5175,
 84.9514]

In [19]:
dfA24F_Ai= pd.to_numeric(dfA24F_A['Freq. A'])
dfA24F_Ai= dfA24F_Ai.values.T.tolist()
dfA24F_Ai

[26.7912,
 52.9486,
 72.1372,
 90.1752,
 113.3914,
 143.6167,
 161.547,
 185.8158,
 205.528,
 232.9498,
 252.146,
 268.2624,
 291.5295,
 310.8275,
 325.5201,
 354.2292,
 391.9073,
 424.6537,
 433.1005,
 462.0133,
 489.4804,
 525.9672,
 558.6097,
 583.6968,
 618.5756,
 655.3342,
 713.6549,
 762.5284,
 805.0978,
 895.275,
 930.5136,
 952.4164,
 1001.5199,
 1018.2434,
 1060.1285,
 1081.51,
 1087.1267,
 1103.62,
 1116.6852,
 1124.9486,
 1135.6887,
 1146.8438,
 1162.8145,
 1174.8063,
 1192.9949,
 1215.7291,
 1240.7734,
 1260.5898,
 1272.0922,
 1294.1737,
 1305.9062,
 1325.8547,
 1334.7285,
 1358.0266,
 1371.0714,
 1379.9977,
 1395.7319,
 1402.0281,
 1407.3193,
 1421.3177,
 1435.1642,
 1439.847,
 1457.713,
 1466.2926,
 1479.7613,
 1495.5923,
 1537.8361,
 1708.8549,
 2998.221,
 3024.5694,
 3030.6098,
 3043.1923,
 3048.5652,
 3065.9462,
 3088.9982,
 3094.2435,
 3110.2672,
 3152.6945,
 3194.1041,
 3698.4985,
 3793.1248,
 3855.0904]

In [20]:
dfA24IRF_A = np.zeros((len(dfA24IR_Ai), 2) )
for n, ir, i  in zip(range(len(dfA24IR_Ai)), dfA24IR_Ai, dfA24F_Ai): 
     dfA24IRF_A[n,0] = ir; dfA24IRF_A[n,1]=i

In [21]:
dfA24IRF_A

array([[2.5820000e-01, 2.6791200e+01],
       [1.4402000e+00, 5.2948600e+01],
       [1.1840000e-01, 7.2137200e+01],
       [3.4640000e+00, 9.0175200e+01],
       [3.0183000e+00, 1.1339140e+02],
       [3.6723000e+00, 1.4361670e+02],
       [1.1562300e+01, 1.6154700e+02],
       [4.5454000e+00, 1.8581580e+02],
       [1.0473020e+02, 2.0552800e+02],
       [4.2934000e+00, 2.3294980e+02],
       [3.7284000e+00, 2.5214600e+02],
       [1.3136000e+00, 2.6826240e+02],
       [3.8180000e-01, 2.9152950e+02],
       [9.4513000e+00, 3.1082750e+02],
       [1.2357600e+01, 3.2552010e+02],
       [1.5848000e+01, 3.5422920e+02],
       [1.4682800e+01, 3.9190730e+02],
       [6.1096000e+01, 4.2465370e+02],
       [7.1023000e+00, 4.3310050e+02],
       [2.1818000e+00, 4.6201330e+02],
       [1.8949600e+01, 4.8948040e+02],
       [4.6491300e+01, 5.2596720e+02],
       [3.3853500e+01, 5.5860970e+02],
       [1.2015470e+02, 5.8369680e+02],
       [1.8994800e+01, 6.1857560e+02],
       [5.6694700e+01, 6.5533420e+02],
       [2.5999600e+01, 7.1365490e+02],
       [3.9647000e+00, 7.6252840e+02],
       [3.6619000e+00, 8.0509780e+02],
       [6.2611000e+00, 8.9527500e+02],
       [1.7731000e+01, 9.3051360e+02],
       [1.7552600e+01, 9.5241640e+02],
       [2.4254000e+00, 1.0015199e+03],
       [1.3729200e+01, 1.0182434e+03],
       [6.0638100e+01, 1.0601285e+03],
       [5.6156000e+01, 1.0815100e+03],
       [3.0215100e+01, 1.0871267e+03],
       [1.3746070e+02, 1.1036200e+03],
       [8.5833800e+01, 1.1166852e+03],
       [1.9475780e+02, 1.1249486e+03],
       [1.4096090e+02, 1.1356887e+03],
       [1.1665400e+02, 1.1468438e+03],
       [4.3564800e+01, 1.1628145e+03],
       [3.4010000e+00, 1.1748063e+03],
       [6.2760900e+01, 1.1929949e+03],
       [8.4037500e+01, 1.2157291e+03],
       [1.7094000e+00, 1.2407734e+03],
       [4.5340900e+01, 1.2605898e+03],
       [2.9719000e+01, 1.2720922e+03],
       [1.1521300e+01, 1.2941737e+03],
       [2.4229000e+00, 1.3059062e+03],
       [6.6320000e-01, 1.3258547e+03],
       [7.1025900e+01, 1.3347285e+03],
       [2.1091700e+01, 1.3580266e+03],
       [3.3150100e+01, 1.3710714e+03],
       [1.8409700e+01, 1.3799977e+03],
       [3.8400800e+01, 1.3957319e+03],
       [4.9237000e+00, 1.4020281e+03],
       [7.7688000e+00, 1.4073193e+03],
       [1.6782400e+01, 1.4213177e+03],
       [6.9295000e+00, 1.4351642e+03],
       [3.9709000e+00, 1.4398470e+03],
       [1.0206700e+01, 1.4577130e+03],
       [7.4927000e+00, 1.4662926e+03],
       [1.0530800e+01, 1.4797613e+03],
       [8.4841000e+00, 1.4955923e+03],
       [1.2924800e+01, 1.5378361e+03],
       [6.8333700e+01, 1.7088549e+03],
       [8.3713000e+00, 2.9982210e+03],
       [5.5106000e+00, 3.0245694e+03],
       [2.3575500e+01, 3.0306098e+03],
       [1.8350500e+01, 3.0431923e+03],
       [2.8505800e+01, 3.0485652e+03],
       [1.7478500e+01, 3.0659462e+03],
       [6.5958000e+00, 3.0889982e+03],
       [4.0466100e+01, 3.0942435e+03],
       [6.6760000e+00, 3.1102672e+03],
       [7.4542000e+00, 3.1526945e+03],
       [6.0401110e+02, 3.1941041e+03],
       [2.9864400e+02, 3.6984985e+03],
       [1.6751750e+02, 3.7931248e+03],
       [8.4951400e+01, 3.8550904e+03]])

In [22]:
broaden=2
def gaussian(X,x0,s):
    return np.exp(-0.5*((X-x0)/s)**2)

def lorentz(X,x0,s):
    return 1/(np.pi*s*(1+((X-x0)/s)**2))

IR_A000A = np.zeros((4001,))
X=np.linspace(0, 4000,4001)
Y=np.zeros((4001,))
for l in range(dfA24IRF_A.shape[0]):
    Y = dfA24IRF_A[l,1]*gaussian(X, dfA24IRF_A[l,0], broaden)
    IR_A000A += Y

In [23]:
 IR_A000A

array([ 5197.03230156,  7982.56884755, 10965.80679881, ...,
           0.        ,     0.        ,     0.        ])

In [24]:
dfA24IR_B.index = pd.RangeIndex(len(dfA24IR_B.index))
dfA24IR_Bi= pd.to_numeric( dfA24IR_B['IR Int. B'])
dfA24IR_Bi= dfA24IR_Bi.values.T.tolist()

dfA24F_B.index = pd.RangeIndex(len(dfA24F_B.index))
dfA24F_Bi= pd.to_numeric(dfA24F_B['Freq. B'])
dfA24F_Bi= dfA24F_Bi.values.T.tolist()

In [25]:
dfA24IRF_B = np.zeros((len(dfA24IR_Bi), 2) )
for n, ir, i  in zip(range(len(dfA24IR_Bi)), dfA24IR_Bi, dfA24F_Bi): 
     dfA24IRF_B[n,0] = ir; dfA24IRF_B[n,1]=i

In [26]:
def gaussian(X,x0,s):
    return np.exp(-0.5*((X-x0)/s)**2)

def lorentz(X,x0,s):
    return 1/(np.pi*s*(1+((X-x0)/s)**2))

IR_A000B = np.zeros((4001,))
X=np.linspace(0, 4000,4001)
Y=np.zeros((4001,))
for l in range(dfA24IRF_A.shape[0]):
    Y = dfA24IRF_B[l,1]*gaussian(X, dfA24IRF_B[l,0], broaden)
    IR_A000B += Y

In [27]:
IR_A000B

array([ 5060.55387921,  7786.19688289, 10589.74427999, ...,
           0.        ,     0.        ,     0.        ])

In [28]:
from scipy import interpolate
import sys
from optparse import OptionParser

In [29]:
def error(msg):
   """ write error message and quit
   """
   sys.stderr.write(msg + "\n")
   sys.exit(3)

In [30]:
def deriv(spec,h):
   """ calculate first derivative of function 'spec'
       using the central finite difference method up to 6th order,
       and for the first 3 and last 3 grid points the
       forward/backward finite difference method up to 2nd order.
       ...as used in f77-program and suggested by Zanazzi-Jona...
   """ 
   der_spec =[[i[0],0] for i in spec]

   length=len(spec)
   for i in range(3,length-3):
      der_spec[i][1]=(-1*spec[i-3][1]+9*spec[i-2][1]-45*spec[i-1][1]+45*spec[i+1][1]-9*spec[i+2][1]+1*spec[i+3][1])/(60*h)
   for i in range(0,3):
      der_spec[i][1]=(-11*spec[i][1]+18*spec[i+1][1]-9*spec[i+2][1]+2*spec[i+3][1])/(6*h)
   for i in range(length-3,length):
      der_spec[i][1]=(11*spec[i][1]-18*spec[i-1][1]+9*spec[i-2][1]-2*spec[i-3][1])/(6*h)

   return der_spec

In [31]:
def get_range(IR_A000A,IR_A000B,w_incr,shift,start,stop):
   """ determine wavenumber range within the comparison between theoretical
       and experimental spectrum is performed (depends on the shift)
   """
   de1=start+shift-IR_A000B[0][0]
   if (de1 >= 0 ):
      de1=int((start+shift-IR_A000B[0][0])/w_incr+0.00001)
      enstart=de1
      tnstart=int((start-IR_A000A[0][0])/w_incr+0.00001)
   else:
      de1=int((start+shift-IR_A000B[0][0])/w_incr-0.00001)
      enstart=0
      tnstart=int((start-IR_A000A[0][0])/w_incr-de1+0.00001)
   de2=stop+shift-IR_A000B[-1][0]
   if (de2 <= 0 ):
      de2=int((stop+shift-IR_A000B[-1][0])/w_incr-0.00001)
      enstop=len(IR_A000B)+de2
      tnstop=len(IR_A000A)+int((stop-IR_A000A[-1][0])/w_incr-0.00001) 
   else:
      de2=int((stop+shift-IR_A000B[-1][0])/w_incr+0.00001)
      enstop=len(IR_A000B)
      tnstop=len(IR_A000A)+int((stop-IR_A000A[-1][0])/w_incr-de2-0.00001)
   return tnstart, tnstop, enstart, enstop

In [32]:
def integrate(integrand,delta):
   """ integrate using the trapezoid method as Zanazzi-Jona suggested and was used in the f77-program...
   """
   integral = 0.5*(integrand[0][1]+integrand[-1][1])   
   for i in range(1,len(integrand)-1):
      integral += integrand[i][1]
   return integral*delta

In [33]:
def ypendry(spec,d1_spec,VI):
   """ calculate the Pendry Y-function: y=l^-1/(l^-2+VI^2) with l=I'/I (logarithmic derivative),
       J.B. Pendry, J. Phys. C: Solid St. Phys. 13 (1980) 937-44
   """
   y=[[i[0],0] for i in spec]

   for i in range(len(spec)):
      if (abs(spec[i][1]) <= 1.E-7):
         if (abs(d1_spec[i][1]) <= 1.E-7):
            y[i][1] = 0 
         else:
            y[i][1] = (spec[i][1]/d1_spec[i][1])/((spec[i][1]/d1_spec[i][1])**2+VI**2)
      else:
         y[i][1] = (d1_spec[i][1]/spec[i][1])/(1+(d1_spec[i][1]/spec[i][1])**2*(VI**2))
   return y

In [34]:

def _main():

   usage = """ %prog [options] r-fac.in
        Reads two spectra and calculates various R-factors -- FS 2011
        Attention: both spectra have to be given on the same, equidistant grid!
        NOTE: in the f77-program R1 is scaled by 0.75 and R2 is scaled by 0.5; this is not done here
        Please provide a file r-fac.in with the following specifications (without the comment lines!!!) 
        (the numbers are just examples, choose them according to your particular case)
        start=1000       # where to start the comparison
        stop=1800        # where to stop the comparison
        w_incr=0.5       # grid interval of the spectra -- should be 1 or smaller! (otherwise integrations/derivatives are not accurate)
        shift_min=-10    # minimal shift of the theoretical spectrum 
        shift_max=+10    # maximal shift of the experimental spectrum
        shift_incr=1     # shift interval
        r=pendry         # which r-factor should be calculated? options: pendry, ZJ, R1, R2 (give a list of the requested r-factors separated by comma)
        VI=10            # approximate half-width of the peaks (needed for pendry r-factor)
        """
   parser = OptionParser(usage=usage)
   parser.add_option("-t","--theory", 
                     default="theory.dat",dest="theory",metavar="filename",
                     help="input file theoretical spectrum [default: %default]")
   parser.add_option("-e","--exp", 
                     default="exp.dat",dest="exp",metavar="filename",
                     help="input file experimental spectrum [default: %default]")

   options, args = parser.parse_args()
   
# read spectra in
   input_theory=open(options.theory)
   tspec=[map(float,line.split()) for line in input_theory.readlines()]
   input_theory.close()
   input_exp=open(options.exp)
   IR_A000B=[map(float,line.split()) for line in input_exp.readlines()]
   input_exp.close()

# read r-fac.in
   if (len(args) != 1):
      error("Please provide r-fac.in and execute: python calc-r-factors.py r-fac.in")
   for line in open(args[0]):
      line=line.split("=")
      if line[0]=="start":
         start=float(line[1])
      elif line[0]=="stop":
         stop=float(line[1])
      elif line[0]=="w_incr":
         w_incr=float(line[1])
      elif line[0]=="shift_min":
         shift_min=float(line[1])
      elif line[0]=="shift_max":
         shift_max=float(line[1])
      elif line[0]=="shift_incr":
         shift_incr=float(line[1])
      elif line[0]=="r":
         r=line[1].split(",") 
         r=[i.strip() for i in r]  # strip off leading and trailing whitespaces
         sys.stdout.write("Requested r-factors: ")
         for i in r:
            sys.stdout.write("%s " % i)
         sys.stdout.write("\nNOTE: in the f77-program R1 is scaled by 0.75 and R2 is scaled by 0.5; this is not done here\n\n")   
      elif line[0]=="VI":
         VI=float(line[1])

# perform some checks of the input data...
   if (int(shift_incr/w_incr+0.00001) == 0):
      error("Error: shift_incr cannot be smaller than w_incr!")
   if (start-IR_A000B[0][0] < 0) or (IR_A000A[-1][0]-stop < 0):
      error("check experimental spectrum!!")
   if (start-IR_A000A[0][0] < 0) or (IR_A000A[-1][0]-stop < 0):
      error("check theoretical spectrum!!")
   if (int((IR_A000B[-1][0]-IR_A000B[0][0])/w_incr+0.0001) != len(IR_A000B)-1 ) or (int((IR_A000A[-1][0]-IR_A000A[0][0])/w_incr+0.0001) != len(IR_A000A)-1 ):
      error("check w_incr!!")

 
# cut out data points that are not needed in order to save time...
   if (IR_A000B[0][0]-(start+shift_min-w_incr*25) < 0):
         IR_A000B=IR_A000A[-1*int((IR_A000A[0][0]-(start+shift_min-w_incr*25))/w_incr-0.00001):][:]
   if (IR_A000B[-1][0]-(stop+shift_max+w_incr*25) > 0):
         IR_A000B=IR_A000B[:-1*(int((IR_A000B[-1][0]-(stop+shift_max+w_incr*25))/w_incr+0.00001)+1)][:] 
   if (IR_A000A[0][0]-(start-w_incr*25) < 0):
         IR_A000A=IR_A000A[-1*int((IR_A000A[0][0]-(start-w_incr*25))/w_incr-0.00001):][:]
   if (IR_A000A[-1][0]-(stop+w_incr*25) > 0):
         IR_A000A=IR_A000A[:-1*(int((IR_A000A[-1][0]-(stop+w_incr*25))/w_incr+0.00001)+1)][:]

   
# set negative intensity values to zero
   for i in range(0,len(IR_A000B)):
      if (IR_A000B[i][1]<0):
         IR_A000B[i][1]=0
   for i in range(0,len(IR_A000A)):
      if (IR_A000A[i][1]<0):
         IR_A000A[i][1]=0
   
# start calculating derivatives...
   d1_espec = deriv(IR_A000B,w_incr)   
   d1_tspec = deriv(IR_A000A,w_incr)
# calculate the second derivatives if the Zanazzi-Jona R-factor is requested   
   if "ZJ" in r:
      d2_tspec = deriv(d1_tspec,w_incr)
      d2_espec = deriv(d1_espec,w_incr)
# calculate Pendry Y-function if Pendry R-factor is requested      
   if "pendry" in r:
      ye = ypendry(espec,d1_espec,VI)
      yt = ypendry(tspec,d1_tspec,VI)
   


   min_pendry = [1.E100,0]
   min_r1     = [1.E100,0]
   min_r2     = [1.E100,0]
   min_zj     = [1.E100,0]
# start with loop over x-axis shifts
   for shift in numpy.arange(shift_min,shift_max+shift_incr,shift_incr):
      # get the interval within the two spectra are compared
      tnstart,tnstop,enstart,enstop = get_range(IR_A000A,IR_A000B,w_incr,shift,start,stop) 
      sys.stdout.write("\nshift: %9.3f, theory-start: %5d, theory-end: %5d, exp-start: %5d, exp-end: %5d\n" % (shift,tspec[tnstart][0],tspec[tnstop-1][0],espec[enstart][0],espec[enstop-1][0]))
      s_espec = numpy.array(IR_A000B[enstart:enstop]) # cut out the interval within which the comparison takes place
      s_tspec = numpy.array(IR_A000A[tnstart:tnstop])
      s_d1_espec = numpy.array(d1_IR_A000B[enstart:enstop])
      s_d1_tspec = numpy.array(d1_IR_A000A[tnstart:tnstop])
      c_scale=integrate(s_espec,w_incr)/integrate(s_tspec,w_incr)
      if "pendry" in r:
         # see J.B. Pendry, J. Phys. C: Solid St. Phys. 13 (1980) 937-44
         s_yt = numpy.array(yt[tnstart:tnstop]) # cut out the interval within which the comparison takes place
         s_ye = numpy.array(ye[enstart:enstop])
         te2 = integrate((s_yt-s_ye)**2,w_incr) # integrate (yt-ye)^2
         t2e2 = integrate(s_yt**2+s_ye**2,w_incr) # integrate yt^2+ye^2
         r_pend = te2/t2e2
         sys.stdout.write("Pendry R-factor : %f, shift: %f\n" % (r_pend,shift))
         if (r_pend < min_pendry[0] ):
            min_pendry=[r_pend,shift]
      if "R1" in r:
         # see  M.A. van Hove, S.Y. Tong, and M.H. Elconin, Surfac Science 64 (1977) 85-95
         r1 = integrate(abs(s_espec-c_scale*s_tspec),w_incr)/integrate(abs(s_espec),w_incr)
         sys.stdout.write("R1 R-factor     : %f, shift: %f\n" % (r1,shift))
         if (r1 < min_r1[0]):
            min_r1=[r1,shift]
      if "R2" in r:
         # see  M.A. van Hove, S.Y. Tong, and M.H. Elconin, Surfac Science 64 (1977) 85-95
         r2 = integrate((s_espec-c_scale*s_tspec)**2,w_incr)/integrate(s_espec**2,w_incr)
         sys.stdout.write("R2 R-factor     : %f, shift: %f\n" % (r2,shift))
         if (r2 < min_r2[0]):
            min_r2=[r2,shift]
      if "ZJ" in r:      
         # E. Zanazzi, F. Jona, Surface Science 62 (1977), 61-88
         s_d2_tspec = numpy.array(d2_tspec[tnstart:tnstop])
         s_d2_espec = numpy.array(d2_espec[enstart:enstop])

         epsilon = 0
         for i in s_d1_espec:
            if abs(i[1]) > epsilon:
               epsilon = abs(i[1])
         
         integrand = abs(c_scale*s_d2_tspec-s_d2_espec)*abs(c_scale*s_d1_tspec-s_d1_espec)/(abs(s_d1_espec)+epsilon)
         # interpolate integrand onto 10 times denser grid, see publication by Zanazzi & Jona
         incr = 0.1*w_incr
         grid_old = numpy.arange(0,len(integrand))*w_incr
         grid_new = numpy.arange(grid_old[0],grid_old[-1]+incr,incr)
         spl = interpolate.splrep(grid_old,integrand.T[1],k=3,s=0)
         integrand_dense = interpolate.splev(grid_new,spl,der=0)
         integrand_dense = numpy.vstack((grid_new,integrand_dense)).T
         # calculate reduced Zanazzi-Jona R-factor r=r/0.027
         r_zj = integrate(integrand_dense,incr)/(0.027*integrate(abs(s_espec),w_incr))
         sys.stdout.write("red. ZJ R-factor: %f, shift %f\n" % (r_zj,shift))
         if (r_zj < min_zj[0]):
            min_zj=[r_zj,shift]


# find minimal r-factor and write it out
   sys.stdout.write("\nMinimal r-factors:\n")
   if "pendry" in r:
      sys.stdout.write("minimal r-factor: Delta = %8.5f, Pendry R-factor = %7.5f \n" % ( min_pendry[1], min_pendry[0]))
   if "R1" in r:
      sys.stdout.write("minimal r-factor: Delta = %8.5f, R1 R-factor = %7.5f \n" % ( min_r1[1], min_r1[0]))
   if "R2" in r:
      sys.stdout.write("minimal r-factor: Delta = %8.5f, R2 R-factor = %7.5f \n" % ( min_r2[1], min_r2[0]))
   if "ZJ" in r:
      sys.stdout.write("minimal r-factor: Delta = %8.5f, ZJ R-factor = %7.5f \n" % ( min_zj[1], min_zj[0]))


if __name__ == "__main__":
      _main()

Usage:  ipykernel_launcher.py [options] r-fac.in
        Reads two spectra and calculates various R-factors -- FS 2011
        Attention: both spectra have to be given on the same, equidistant grid!
        NOTE: in the f77-program R1 is scaled by 0.75 and R2 is scaled by 0.5; this is not done here
        Please provide a file r-fac.in with the following specifications (without the comment lines!!!)
        (the numbers are just examples, choose them according to your particular case)
        start=1000       # where to start the comparison
        stop=1800        # where to stop the comparison
        w_incr=0.5       # grid interval of the spectra -- should be 1 or smaller! (otherwise integrations/derivatives are not accurate)
        shift_min=-10    # minimal shift of the theoretical spectrum
        shift_max=+10    # maximal shift of the experimental spectrum
        shift_incr=1     # shift interval
        r=pendry         # which r-factor should be calculated? options: pendry, ZJ, R1, R2 (give a list of the requested r-factors separated by comma)
        VI=10            # approximate half-width of the peaks (needed for pendry r-factor)


ipykernel_launcher.py: error: no such option: -f

SystemExit: 2

/home/crpbn/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2886: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)